# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Poliehov/image_processing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Poliehov/image_processing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Poliehov/image_processing/CMakeFiles /home/user/Poliehov/image_processing//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Poliehov/image_processing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cge

# Build rule for target.
cge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cge
.PHONY : cge

# fast build rule for target.
cge/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/build
.PHONY : cge/fast

color.o: color.cpp.o
.PHONY : color.o

# target to build an object file
color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/color.cpp.o
.PHONY : color.cpp.o

color.i: color.cpp.i
.PHONY : color.i

# target to preprocess a source file
color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/color.cpp.i
.PHONY : color.cpp.i

color.s: color.cpp.s
.PHONY : color.s

# target to generate assembly for a file
color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/color.cpp.s
.PHONY : color.cpp.s

frame_generators/cge_sdl2.o: frame_generators/cge_sdl2.cpp.o
.PHONY : frame_generators/cge_sdl2.o

# target to build an object file
frame_generators/cge_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/frame_generators/cge_sdl2.cpp.o
.PHONY : frame_generators/cge_sdl2.cpp.o

frame_generators/cge_sdl2.i: frame_generators/cge_sdl2.cpp.i
.PHONY : frame_generators/cge_sdl2.i

# target to preprocess a source file
frame_generators/cge_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/frame_generators/cge_sdl2.cpp.i
.PHONY : frame_generators/cge_sdl2.cpp.i

frame_generators/cge_sdl2.s: frame_generators/cge_sdl2.cpp.s
.PHONY : frame_generators/cge_sdl2.s

# target to generate assembly for a file
frame_generators/cge_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/frame_generators/cge_sdl2.cpp.s
.PHONY : frame_generators/cge_sdl2.cpp.s

frame_process.o: frame_process.cpp.o
.PHONY : frame_process.o

# target to build an object file
frame_process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/frame_process.cpp.o
.PHONY : frame_process.cpp.o

frame_process.i: frame_process.cpp.i
.PHONY : frame_process.i

# target to preprocess a source file
frame_process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/frame_process.cpp.i
.PHONY : frame_process.cpp.i

frame_process.s: frame_process.cpp.s
.PHONY : frame_process.s

# target to generate assembly for a file
frame_process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/frame_process.cpp.s
.PHONY : frame_process.cpp.s

image_formats/cge_png.o: image_formats/cge_png.cpp.o
.PHONY : image_formats/cge_png.o

# target to build an object file
image_formats/cge_png.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/image_formats/cge_png.cpp.o
.PHONY : image_formats/cge_png.cpp.o

image_formats/cge_png.i: image_formats/cge_png.cpp.i
.PHONY : image_formats/cge_png.i

# target to preprocess a source file
image_formats/cge_png.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/image_formats/cge_png.cpp.i
.PHONY : image_formats/cge_png.cpp.i

image_formats/cge_png.s: image_formats/cge_png.cpp.s
.PHONY : image_formats/cge_png.s

# target to generate assembly for a file
image_formats/cge_png.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/image_formats/cge_png.cpp.s
.PHONY : image_formats/cge_png.cpp.s

image_formats/cge_ppm.o: image_formats/cge_ppm.cpp.o
.PHONY : image_formats/cge_ppm.o

# target to build an object file
image_formats/cge_ppm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/image_formats/cge_ppm.cpp.o
.PHONY : image_formats/cge_ppm.cpp.o

image_formats/cge_ppm.i: image_formats/cge_ppm.cpp.i
.PHONY : image_formats/cge_ppm.i

# target to preprocess a source file
image_formats/cge_ppm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/image_formats/cge_ppm.cpp.i
.PHONY : image_formats/cge_ppm.cpp.i

image_formats/cge_ppm.s: image_formats/cge_ppm.cpp.s
.PHONY : image_formats/cge_ppm.s

# target to generate assembly for a file
image_formats/cge_ppm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/image_formats/cge_ppm.cpp.s
.PHONY : image_formats/cge_ppm.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cge.dir/build.make CMakeFiles/cge.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cge"
	@echo "... color.o"
	@echo "... color.i"
	@echo "... color.s"
	@echo "... frame_generators/cge_sdl2.o"
	@echo "... frame_generators/cge_sdl2.i"
	@echo "... frame_generators/cge_sdl2.s"
	@echo "... frame_process.o"
	@echo "... frame_process.i"
	@echo "... frame_process.s"
	@echo "... image_formats/cge_png.o"
	@echo "... image_formats/cge_png.i"
	@echo "... image_formats/cge_png.s"
	@echo "... image_formats/cge_ppm.o"
	@echo "... image_formats/cge_ppm.i"
	@echo "... image_formats/cge_ppm.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

